# Generated by Django 6.1.1 on 2026-09-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0004_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
